### ISSUE TITLE
How to perform a `ILIKE` filter ?

### ISSUE THREAD

**Issue by Bopzor** [Soontao/light-odata#189]
Hello,

I'm new to using `odata`, and I'm looking for a way to perform a `ILIKE` filter in `odata v2`.

I find in [odata documentation](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) that it might be possible using a function (`bool substringof(string po, string p1)`), but I'm not sure `light-odata` already support it (?).

Does anyone know another way to do it?

Thanks for your time :)

**Comment by Soontao** [comment]
Hello @Bopzor 

Following snippet is a code sample for the offical sample service https://services.odata.org/V2/Northwind/Northwind.svc/Customers, hope you like this.

https://github.com/Soontao/light-odata/blob/4f002195e2af9f90bf77431b2e25508c17a8023a/tests/read.spec.ts#L104-L143

BR.

**Comment by Bopzor** [comment]
Hi, thank you @Soontao!

I used `client.newFilter().field("indexof(CompanyName, 'Futterkiste')").gt(-1)` and it works like a charm!

Would you like me to open a PR to add an example in the `README.md`?

Thanks for your work (Typescript feels nice :fire:) and I really appreciate your reactivity too.

**Comment by Soontao** [comment]
@Bopzor 
sure, absolutely welcome
just add to the ‘odata filter’ charter please.

**Comment by Soontao** [comment]
closed by #190 
thanks @Bopzor contribution. :)
