### ISSUE TITLE
Support for null query

### ISSUE THREAD

**Issue by ErnieBernie10** [Soontao/light-odata#253]
I want to use a filter that would generate a query like: ``$filter=Name eq null`` but this is not currently possible. Passing null to the ``eq`` function is not possible and passing null as a string puts it between quotes like ``'null'``

Is there any way around this and if not can this feature be added?

**Comment by Soontao** [comment]
Let me check about this

**Comment by Soontao** [comment]
Hello @ErnieBernie10 

Sorry for the late reply, I've released a new version `2.13.0` to support create filter with `null`

```js
const filter = OData.newFilter().field("Phone").eq(null)
```

if you can not upgrade the version of `@odata/client`, you can easily create a param with free text

```js
const param = OData.newParam().filter("Name eq null")
```

Thanks

**Comment by ErnieBernie10** [comment]
I actually updated the package and there's still no support for ``null`` When looking at the code in the repo I also see the type of the eq param does not accept null. Not sure if I'm just missing something or what.

**Comment by Soontao** [comment]
Hello @ErnieBernie10, 

Could you provide more information about your project, with some code snippet or error statck?

Here are the unit test about `eq null`

https://github.com/Soontao/light-odata/blob/3822266c51bb5fbc6636332a20316e3d7cca6643/tests/filter.spec.ts#L17-L20

https://github.com/Soontao/light-odata/blob/3822266c51bb5fbc6636332a20316e3d7cca6643/tests/read.spec.ts#L84-L92

Thanks :)

**Comment by ErnieBernie10** [comment]
I'm talking about the parameter type definition of ``eq`` here:
https://github.com/Soontao/light-odata/blob/3822266c51bb5fbc6636332a20316e3d7cca6643/src/filter.ts#L127-L130

It does not accept null. Perhaps it would work when using plain js but the typescript compiler complains

**Comment by Soontao** [comment]
Hi @ErnieBernie10 ,

I guess you are using `strictNullChecks` in your ts config, you can simplely disable it in `compileOptions`, or, try the new version `2.14.0`, I've added the `null` to the method declaration.

Thanks, have a nice day :)
