### ISSUE TITLE
visibility of getCsrfToken() method

### ISSUE THREAD

**Issue by tdespres** [Soontao/light-odata#416]
Hello Soontao,

Is it possible to change the visibility of the `getCsrfToken()` method to **public** ?
https://github.com/Soontao/light-odata/blob/011e5dfd4dc6050ee3a872eb8d2aa071a0a3cc58/src/request.ts#L259

For some reasons, I need to fetch/get the `x-crsf-token` without doing an odata request.
In SAPUI5 framework, you can get this token using the `getSecurityToken()` method: 
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.model.odata.v2.ODataModel%23methods/getSecurityToken

Thanks for you help,

BR,

**Comment by Soontao** [comment]
Hi @tdespres 

sure, let me review it firstly, then I will update this issue, maybe change visibility or provide a new method for csrf token

Regards,
Theo

**Comment by Soontao** [comment]
Hi @tdespres 

I've released new version `2.18.0`, and as you wanted, the of visibility the `getCsrfToken` method has been changed to `public`

have a nice day :)

regards,
Theo

**Comment by tdespres** [comment]
Hello @Soontao

Thanks for your reactivity.
The use of "Mutex" is very nice and will resolve some issues.

regards
