### ISSUE TITLE
Client is not properly closing itself

### ISSUE THREAD

**Issue by sherlock1982** [Soontao/light-odata#417]
`ClientCredentialsOAuthClient` has a function destroy() to call `clearInterval()`

Unfortunately there's no way to call this function from `OData` type itself as `ClientCredentialsOAuthClient` is private there.

Hanging `setInterval()` prevents proper Node shutdown.

`destroy()` function should be exposed. 

On the other hand it's not clear why do you need to have `setInterval()` at all because you can simply check expiration of OAuth token on the next call.

**Comment by Soontao** [comment]
Hi @sherlock1982 

Yes, you're right, in a short the `setInterval` could ensure the token retrieving only be processed one time in same time but also be a simple implementation for token refresh.

I'll change this part, and update the status in this issue later.

Regards,
Theo

**Comment by sherlock1982** [comment]
Up to you but I suggest to remove setInterval(). Simply store the expiration time and re-request the token when a new request comes and you think the token expired. Cons:

1. You refresh the token even if no request comes. There's no point - maybe no request will ever come but you keep refreshing it for nothing.

2. Expiration time is set only on the first response. What if next response will have a different expiration time? Well highly unlikely but generally possible.

**Comment by Soontao** [comment]
Hi @sherlock1982,

Really thanks for your long description, maybe we have some misunderstandings, but in fact totally I agree with all statements from you :).

in fact I dont realized that will have person use the oauth client, and there is no document describe that, and no unit test for that, haha. 

I would remove the timer for a number of reasons, meanwhile, I'll add unit test for that.

Have a nice day :) 

Regards,
Theo

**Comment by Soontao** [comment]
HI @sherlock1982 

Thanks for your useful suggestion and now, the timer has been removed from the oauth client, I also have added some ut/fix for that.

The alpha/beta version of 2.19.0 has applied this change. 

Regards,
Theo
