### ISSUE TITLE
Is it possible to set custom headers?

### ISSUE THREAD

**Issue by MarioKiese** [Soontao/light-odata#420]
Hello Soontao,

at first: This library is great work. Thank you for this.

Now back to my question. Is it possible to set additional headers e.g. to pass a Bearer token?

Best regards.

**Comment by Soontao** [comment]
Hi @MarioKiese, 

thanks for your question firstly, as your request, I released a new version `2.19.4`, which introduce back the `commonHeaders` to the `options` of `OData.New`, just ref the README doc https://github.com/Soontao/light-odata#common-headers to get help.

By the way, if you are using oauth client credential to retrieve the Bearer token and pass it to target service, maybe `OData.New(options.credentials.oauthXXXX)` could help you. https://github.com/Soontao/light-odata/blob/b42773d057bfe0b8ecf55285ddaae237fa55dc58/src/types.ts#L200-L225

Regards,
Theo

**Comment by MarioKiese** [comment]
Thank you, @Soontao . Works perfectly 👍.

Best regards,
Mario
