### ISSUE TITLE
Nested expand

### ISSUE THREAD

**Issue by MarioKiese** [Soontao/light-odata#422]
Hi @Soontao,

is it possible to have a nested expand like in the following example:

`const expand = OData.newParam().expand('to_ConnectionObjectNotes/to_NoteText/to_NoteTextT')`

I get an error when I execute the request with the expand above: 

"error": Object {
    "code": "400",
    "message": "Expected uri token 'STAR' could not be found in 'to_ConnectionObjectNotes/to_NoteText/to_NoteTextT' at position 26",
  },

In general the URL for the request would look like the following, but I don't know how the library handles it in version 2.19.4:

http://localhost:4004/odata-service/Reading?$expand=to_ConnectionObjectNotes/to_NoteText/to_NoteTextT

Best regards
Mario

**Comment by Soontao** [comment]
try this if you are using odata v4 and 'to_xxxx' is navagation

```js
OData.newParam().expand('to_ConnectionObjectNotes($expand=to_NoteText)')
```

**Comment by MarioKiese** [comment]
Thanks @Soontao! Works like a charm 👍. 

Best regards
Mario
