### ISSUE TITLE
[Question] How to read all records from a collection

### ISSUE THREAD

**Issue by ykgw-swamy** [Soontao/light-odata#455]
## System Environment

* OS: Windows 10
* NodeJS Version:  16.14.2
* This LIbrary Version: 2.20.1

## I want to read all records for a given collection, currently I could only read 200 records.

> I'm trying to read all the items in Orders collection from Northwind OData V4 service. I could only read 200 records and get "@Odata.nextlink" in reply. I tried making 2nd call by appending nextlink to the url, but I still get back same first 200 records. Can somebody help me with some example on how to do it?

> for reference I want ti implement "Get All Records" feature highlighted in below screen.
![image](https://user-images.githubusercontent.com/79636976/180382768-77f07674-db65-4465-9490-1579482b60bc.png)

>Below is the sample code I've tried

```
let client = OData.New({ metadataUri: url, version: "v4"});
let result = await client.newRequest({
  collection: "Orders",
  params: OData.newParam().select("OderID"),
});
urlNew = url + result["@odata.nextLink"]
var finished = result["@odata.nextLink"] === undefined

do {
  let clientlocal = OData.New({ metadataUri: urlNew , version: "v4" });
  let resultlocal = await clientlocal.newRequest({
    collection: "Orders",
    params: OData.newParam().select("OderID"),
  });
  urlNew = url + result["@odata.nextLink"]
  finished = resultlocal["@odata.nextLink"] === undefined
} while (!finished)
```

**Comment by Soontao** [comment]
not supported out of box, but the most quick way i think is specify a large `$top` (in param) value, like 100000.

 most of odata service has a default `$top` value for many reasons, you can try to overrite that.
