### ISSUE TITLE
Getting fetch not defined error[Question]

### ISSUE THREAD

**Issue by swamy2712** [Soontao/light-odata#512]
## System Environment

* OS: Windows 10
* NodeJS Version: 14.17.0
* This LIbrary Version: 2.20.1

## Question Description
I'm getting **ReferenceError: fetch is not defined**  when I try to use **client.newRequest** API as shown below.

![image](https://user-images.githubusercontent.com/4666902/192526657-0bb845b7-c7be-490b-8b7c-21463fa39d44.png)

> The error happens when line 32 is executed in **@odata\\client\\lib\\request.js:32** file. 
I added `const fetch = require("node-fetch");` line in **@odata\client\lib\request.js** file and error was resolved. I'm not sure what is the problem, can anyone please help me to resolve this issue ?

**Comment by Soontao** [comment]
hi @swamy2712 

have a look at this doc, it should work with nodejs

https://github.com/Soontao/light-odata/blob/main/docs/Advanced.md#server-side-polyfill

```js

// import "@odata/client/lib/polyfill"
require("@odata/client/lib/polyfill")

// use OData

```
