### ISSUE TITLE
Shouldn't this be typed?

### ISSUE THREAD

**Issue by Megamannen** [Soontao/light-odata#545]
Just stumbled upon this when trying out this lib, shouldn't this row be typed?

https://github.com/Soontao/light-odata/blob/0a87b246e759071e1716379ccb69e66938f1f488/src/filter.ts#L267
(and maybe https://github.com/Soontao/light-odata/blob/0a87b246e759071e1716379ccb69e66938f1f488/src/filter.ts#L260)

```ts
static newFilter<T = any>(): ODataFilter<T> {
```

I don't see how the `keyof` in property will ever be other than `any` if this change isn't made

**Comment by Soontao** [comment]
[2.21.0](https://github.com/Soontao/light-odata/tree/v2.21.0) was released for this.
