### ISSUE TITLE
Is there an way to set client SSL certificates

### ISSUE THREAD

**Issue by swamy2712** [Soontao/light-odata#652]
Hello @Soontao,

As the title says, is there a way to set client ssl certificates (key, cert and ca) ?

**Comment by Soontao** [comment]
Hi @swamy2712 

maybe you can check this doc firslty: https://github.com/Soontao/light-odata/blob/main/docs/Advanced.md#fetch-proxy

use `fetchProxy` parameter and use our familiar nodejs client with certification authentication. 

BR,
Theo

**Comment by swamy2712** [comment]
Hi @Soontao,

Thank you for your response. using `fetchproxy` helped. I wanted to know what to return during error. For example if URL is unreachable/incorrect. The link you shared does not address this situation.
