### ISSUE TITLE
while using batch feature, I always got "multipartBody.split is not a function" error[Question]

### ISSUE THREAD

**Issue by jessicali001** [Soontao/light-odata#762]
## System Environment

* OS:
* NodeJS Version: 
* This LIbrary Version:

## Question Description

> add some question description here
I am trying to use batch feature, I followed the example(https://github.com/Soontao/light-odata/blob/74d2d0cfe2f1285482f8f3ca763db51b7df9446a/docs/Batch.md) provided, but got error as below
TypeError: multipartBody.split is not a function
    at parseMultiPartContent (XXX\@odata\client\lib\batch.js:128:37)
    at OData.execBatchRequests (XXX\node_modules\@odata\client\lib\odata.js:408:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Please advise, thanks!

**Comment by Soontao** [comment]
Hi @jessicali001 

could you provide more information about your setup ? frontend/backend ? node version? did you use the customized `fetchProxy` ? 

looks like `fetchProxy` does not return correct `content` then later parsing logic failed. 

BR,
Theo

**Comment by Soontao** [comment]
Hi @jessicali001 

sorry we cannot reproduce this in our odata service, could you try to manually create $batch payload and get the response header/content to us.

we guess there are something not handled correctly for response. 

BR,
THeo
