### ISSUE TITLE
[Question] How to use in this library in a browser environment

### ISSUE THREAD

**Issue by gh7531** [Soontao/light-odata#935]
## System Environment

* OS: MacOS 14.4.1
* NodeJS Version: none, I'm trying to load the library using a <script> tag in the latest firefox and chrome browser
* This LIbrary Version: 2.21.9 from unpgk.com

## Question Description

> I am currently working on a legacy project where it is hard to add libraries using npm/yarn, therefore I tried to import the library using <script> tags as described in the README.md. 
However it seem like the OData object is not added to the window object. I can see that the `odata-client-umd.js` file is fetched during load but nothing is added to the window object. 
Other libraries I tried to import using a CDN like vue.js and axios are working as expected.

Here is an example `index.html` to show what I tried to do.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios@1.6.7/dist/axios.min.js"></script>
    <script src="https://unpkg.com/@odata/client@2.21.9/lib/odata-client-umd.js"></script>
</head>
<body>
<script>
    console.log(window)
    console.log(Vue)
    console.log(axios)
    console.log(OData)
</script>
</body>
</html>
```

I assume the issue is just me not understanding something obvious, but I would appreciate any help you can give me since this library looks awesome.

Best regards.

**Comment by Soontao** [comment]
good question, issue relevant https://github.com/evanw/esbuild/issues/507 

will check alternative approach.

**Comment by Soontao** [comment]
Hi @gh7531 

build script issue, please try https://unpkg.com/@odata/client@2.21.10/lib/odata-client-umd.js

have a nice day :)

BR,
THeo

**Comment by gh7531** [comment]
Thank you very much, it seems to work 👍
